config/routes.rb
Rails.application.routes.draw do
  root 'carts#index'
  resources :cart_products
  resources :carts do
    get :add_products, on: :member
  end
  resources :products
  resources :cities
  devise_for :users, controllers: { registrations: 'user/registrations' }

  namespace :api do
    post :update, as: "add_product", to: "carts#update"
  end
end

app/models/cart_product.rb
# coding: utf-8
# == Schema Information
#
# Table name: cart_products
#
#  id         :integer          not null, primary key
#  cart_id    :integer
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string
#  photo_url  :string
#

class CartProduct < ActiveRecord::Base
  belongs_to :cart
  validates :quantity, numericality: { greater_than: 0 }

  def image
    return photo_url if photo_url.present?
    "http://placehold.it/100x100"
  end

  def bulk_price
    "#{quantity * 2} zł"
  end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :set_cart_product, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to root_path, notice: 'Wrong'
  end

  def show
    redirect_to cart_path(@cart_product.cart_id)
  end

  def new
    @cart_product = CartProduct.new
  end

  def edit
  end

  def create
    @cart_product = CartProduct.new(cart_product_params)

    respond_to do |format|
      if @cart_product.save
        format.html { redirect_to @cart_product, notice: 'Cart product was successfully created.' }
        format.json { render :show, status: :created, location: @cart_product }
      else
        format.html { render :new }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart_product.update(cart_product_params)
        format.html { redirect_to @cart_product, notice: 'Cart product was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_product }
      else
        format.html { render :edit }
        format.json { render json: @cart_product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart_product.destroy
    respond_to do |format|
      format.html { redirect_to cart_products_url, notice: 'Cart product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_cart_product
    @cart_product = CartProduct.find(params[:id])
  end

  def cart_product_params
    params.require(:cart_product).permit(:cart_id, :quantity)
  end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/_form.html.haml
= simple_form_for(@cart_product) do |f|
  = f.error_notification

  .form-inputs
    = f.input :cart_id
    = f.input :quantity

  .form-actions
    = f.button :submit

app/views/cart_products/edit.html.haml
%h1 Editing cart_product

= render 'form'

= link_to 'Show', @cart_product
\|
= link_to 'Back', cart_products_path

app/views/cart_products/index.html.haml
%h1 Listing cart_products

%table
  %thead
    %tr
      %th Cart
      %th Product
      %th Quantity
      %th
      %th
      %th

  %tbody
    - @cart_products.each do |cart_product|
      %tr
        %td= cart_product.cart_id
        %td= cart_product.quantity
        %td= link_to 'Show', cart_product
        %td= link_to 'Edit', edit_cart_product_path(cart_product)
        %td= link_to 'Destroy', cart_product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart product', new_cart_product_path

app/views/cart_products/new.html.haml
%h1 New cart_product

= render 'form'

= link_to 'Back', cart_products_path

app/views/cart_products/show.html.haml
%p
  %b Cart:
  = @cart_product.cart_id
%p
  %b Quantity:
  = @cart_product.quantity

= link_to 'Edit', edit_cart_product_path(@cart_product)
\|
= link_to 'Back', cart_products_path