config/routes.rb
Rails.application.routes.draw do
  root 'carts#index'
  resources :cart_products
  resources :carts do
    get :add_products, on: :member
  end
  resources :products
  resources :cities
  devise_for :users, controllers: { registrations: 'user/registrations' }

  namespace :api do
    post :update, as: "add_product", to: "carts#update"
  end
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  city_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string
#

class Cart < ActiveRecord::Base
  belongs_to :city
  has_many :cart_products

  def products
    self.cart_products
  end
end

app/controllers/api/carts_controller.rb
require "net/http"
require "uri"
module Api
  class CartsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def update
      @cart = City.where(region_name: params[:region_name]).first.carts.first_or_create
      correct_uri = params[:product_link].slice(1..-2)
      pip_id = correct_uri.split('/').last
      @product = Product.where(pip_id: pip_id).first || Product.new(pip_id: pip_id)

      if @product.name.blank?
        uri = URI.parse(correct_uri)
        response = Net::HTTP.get_response(uri)
        @product.name = response.body.scan(/(?<=itemprop=\"name\">)(.*)(?=<)/).first.first || ""
        @product.save
      end

      @cart_product = CartProduct.new
      @cart_product.cart_id = @cart.id
      @cart_product.quantity = params[:product_amount]
      @cart_product.save
      render json: @cart_product
    end

    private

    def cart_params
      params.require(:cart).permit(:region_name, :product_link, :product_amount)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  expose(:cart)

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  def add_products
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:city_id, :name)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.haml
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :city_id, label: false, input_html: { value: current_user.city_id, type: 'hidden' }

  .form-actions
    = f.button :submit

app/views/carts/_product_list.html.haml
%ul.collection.highlight
  - @cart.products.each do |product|
    %li.collection-item.avatar
      %img{'src': product.image, 'alt': product.name, 'class': 'circle'}
      %span.title
        = product.name
      %p
        Quantity:
        %span.product-quantity
          = product.quantity
        %br
        Price:
        %span.product-price
          = product.bulk_price
      %a{'href': '#!', 'class': 'secondary-content'}
        %i.material-icons.inc-product
          add
        %i.material-icons.dec-product
          remove

.row
  .col.s12.m4.l2
    %a.btn.waves-effect.waves-light.new-product-btn{href: add_products_cart_path(cart)}
      Add new product
      %i.material-icons.right
        send
  .col.s12.m4.l8.divider
  .col.s12.m4.l2
    %button.btn.waves-effect.waves-light.sync-btn
      Sync
      %i.material-icons.right
        send

app/views/carts/add_products.haml
%h5
  Add new product to #{cart.name}!

%p
  To add new product to card provide its ID or complete URL:
%form{class: 'new-product-form', method: 'post', action: cart_products_path}
  %input{type: 'hidden', name: 'authenticity_token', value: form_authenticity_token}
  %input{type: 'hidden', name: 'cart_product[cart_id]', value: cart.id}
  .input-field
    %input{type: 'text', id: 'product-id', name: 'cart_product[id]'}
    %label{class: 'active', for: 'product-id'}
      Product ID:
  .input-field
    %input{type: 'text', id: 'product-link', name: 'cart_product[link]'}
    %label{class: 'active', for: 'product-link'}
      Product link:
  .input-field
    %input{type: 'number', id: 'product-quantity', name: 'cart_product[quantity]'}
    %label{class: 'active', for: 'product-quantity'}
      Product quantity:
  .input-field
    %button.btn.waves-effect.waves-light.add-cart-btn{type: 'submit'}
      Add product
      %i.material-icons.right
        send

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h5 Available carts:

%table.highlight
  %thead
    %tr
      %th City name
      %th Actions

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to cart.name, cart
        %td
          %a.tooltipped{href: add_products_cart_path(cart), data: { tooltip: 'Add product to cart'} }
            %i.material-icons
              add
          %a.tooltipped.delete-cart{href: cart_path(cart), data: { method: 'delete', tooltip: 'Delete cart' } }
            %i.material-icons
              remove

%br

%a.btn.waves-effect.waves-light{href: new_cart_path}
  Create new cart
  %i.material-icons.right
    send

app/views/carts/new.html.haml
%h5 Add new cart!

%form{class: 'new-cart-form', method: 'post', action: carts_path}
  %input{type: 'hidden', name: 'authenticity_token', value: form_authenticity_token}
  .input-field
    %input{type: 'text', id: 'cart-name', name: 'cart[name]'}
    %label{class: 'active', for: 'cart-name'}
      Cart name:
  .input-field
    %select{name: 'city', class: 'city-select'}
      - City.all.each do |city|
        %option{value: city.id, selected: (current_user.city.id == city.id)}
          = city.region_name.capitalize
    %label
      City
  .input-field
    %button.btn.waves-effect.waves-light.add-cart-btn{type: 'submit'}
      Add cart
      %i.material-icons.right
        send

app/views/carts/show.html.haml
%p
  %h5
    Showing products for cart:
    = @cart.name
- if @cart.products.empty?
  Looks like you don't have any products in your cart!
  %br
  Perhaps would you like to add a new one?
  %p
    %a.btn.waves-effect.waves-light{href: add_products_cart_path}
      YES!
      %i.material-icons.right
        send
- else
  = render 'product_list', products: @cart.products