config/routes.rb
Rails.application.routes.draw do
  root 'carts#index'
  resources :cart_products
  resources :carts do
    get :add_products, on: :member
  end
  resources :products
  resources :cities
  devise_for :users, controllers: { registrations: 'user/registrations' }

  namespace :api do
    post :update, as: "add_product", to: "carts#update"
  end
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id          :integer          not null, primary key
#  region_name :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class City < ActiveRecord::Base
  has_many :users
  has_many :carts
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:region_name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.haml
= simple_form_for(@city) do |f|
  = f.error_notification

  .form-inputs
    = f.input :region_name

  .form-actions
    = f.button :submit

app/views/cities/edit.html.haml
%h1 Editing city

= render 'form'

= link_to 'Show', @city
\|
= link_to 'Back', cities_path

app/views/cities/index.html.haml
%h1 Listing cities

%table
  %thead
    %tr
      %th Region name
      %th
      %th
      %th

  %tbody
    - @cities.each do |city|
      %tr
        %td= city.region_name
        %td= link_to 'Show', city
        %td= link_to 'Edit', edit_city_path(city)
        %td= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New City', new_city_path

app/views/cities/new.html.haml
%h1 New city

= render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.haml
%p
  %b Region name:
  = @city.region_name

= link_to 'Edit', edit_city_path(@city)
\|
= link_to 'Back', cities_path